### ISSUE TITLE
1.86.0 version makes code chunks non-executable in VS Code

### ISSUE THREAD

**Issue by MiguelCos** [quarto-dev/quarto#184]
Hello, thanks a lot for your work on quarto!

I'm reporting something that definitely looks like a bug in the latest release.

The following screenshot is taken while quarto 1.85.0 is active.
![image](https://github.com/quarto-dev/quarto/assets/33185213/5a0ed4d3-09c2-4a2b-bc34-627b1e7d15c9)

The next is taken while quarto 1.86.0 is active.
![image](https://github.com/quarto-dev/quarto/assets/33185213/806e8522-4fc3-4259-8330-9f360848932f)

The code chunks are not executable.

I noticed this while running quarto and R code. 

It seems the update was automatic, because it was working >5 hours ago and then it didn't... For some reason I noticed the recent update and there it was :)

Best,
Miguel

**Comment by afsilvad** [comment]
Same thing, I've downgraded to v.1.85.0 in the hope that the problem will be solved in future updates

**Comment by jjallaire** [comment]
I think that the issue here is that in v1.86.0 we switched to using Pandoc to parse markdown (i.e. to determine where the code chunks are). If the extension is unable to find Quarto on your system then it will exhibit this behavior. If you don't mind, a couple of things to try:

(1) Re-install 1.86 and then execute the **Developer: Toggle Developer Tools** command. Then click on the "Console" tab in the developer tools and execute **Developer: Reload Window**. Then try to use Quarto features. You will very possibly see an error logged there that might help explain what's going on.

(2) Try executing `which quarto` in the Terminal -- does it find a version of Quarto on the PATH?

(3) Finally, try setting the `quarto.path` configuration setting to the full path to the Quarto binary on your system and then reloading again. Do the commands show up now?

**Comment by wjdenny** [comment]
I'm having the same issue. It was working yesterday and must have updated recently. 

I tried the steps in (1). `quarto.path` matches `which quarto` which finds a version of Quarto on the PATH.

I'm getting these errors in the console related to quarto, but can't quite make sense of them.
```
workbench.desktop.main.js:624   ERR [Extension Host] Error running filter /home/user/.vscode-oss/extensions/quarto.quarto-1.86.0-universal/out/lsp/resources/parser.lua:
Unexpected type: TypeUserdata
	while retrieving value
	while retrieving key-value pair
	while retrieving value
	while retrieving key-value pair
stack traceback:
	...rto.quarto-1.86.0-universal/out/lsp/resources/parser.lua:168: in function <...rto.quarto-1.86.0-universal/out/lsp/resources/parser.lua:149>
workbench.desktop.main.js:97 [Extension Host] Error running filter /home/user/.vscode-oss/extensions/quarto.quarto-1.86.0-universal/out/lsp/resources/parser.lua:
Unexpected type: TypeUserdata
	while retrieving value
	while retrieving key-value pair
	while retrieving value
	while retrieving key-value pair
stack traceback:
	...rto.quarto-1.86.0-universal/out/lsp/resources/parser.lua:168: in function <...rto.quarto-1.86.0-universal/out/lsp/resources/parser.lua:149>
I @ workbench.desktop.main.js:97
$logExtensionHostMessage @ workbench.desktop.main.js:1532
N @ workbench.desktop.main.js:1532
M @ workbench.desktop.main.js:1532
H @ workbench.desktop.main.js:1532
G @ workbench.desktop.main.js:1532
(anonymous) @ workbench.desktop.main.js:1532
invoke @ workbench.desktop.main.js:93
deliver @ workbench.desktop.main.js:93
fire @ workbench.desktop.main.js:93
fire @ workbench.desktop.main.js:564
q.onmessage @ workbench.desktop.main.js:1630
workbench.desktop.main.js:1629 Extension Host
workbench.desktop.main.js:1629 Error running filter /home/user/.vscode-oss/extensions/quarto.quarto-1.86.0-universal/out/lsp/resources/parser.lua:Unexpected type: TypeUserdata	while retrieving value	while retrieving key-value pair	while retrieving value	while retrieving key-value pairstack traceback:	...rto.quarto-1.86.0-universal/out/lsp/resources/parser.lua:168: in function <...rto.quarto-1.86.0-universal/out/lsp/resources/parser.lua:149>
workbench.desktop.main.js:624  INFO [perf] Render performance baseline is 24ms
```

**Comment by jjallaire** [comment]
Thank you! I Do you know what version of Quarto you are running? `quarto --version` should let you know.

I just pushed another version of the extension (v1.86.1) which will show a message at startup if Quarto isn't found. In this case though Quarto is being found but I think there is a compatibility issue with the version of Quarto/Pandoc you have. In the new version you can also execute the **Quarto: Verify Installation** command to check what version is being detected by the extension.

**Comment by jjallaire** [comment]
Never mind, I've now reproduced the problem on Quarto v1.3 (was doing development against v1.4). Should have a fix shortly!

**Comment by jjallaire** [comment]
Okay, v1.86.2 has the fix and is now available on the marketplace. This fix tested all the way back to v1.0 of Quarto :-) 

Thanks to everyone who reported the problem and provided the additional diagnostics required to get to the bottom of it!

**Comment by alexbstl** [comment]
I am still getting this issue with old files that I created in 1.85 or earlier.  I am also getting errors similar to [this](https://github.com/quarto-dev/quarto/issues/189#issue-1732054524).  Downgrading to Quarto 1.85 makes everything behave as expected.  I am a little new to Quarto and unsure if I am doing anything wrong, but I have this same issue on VSCode on macOS, Linux and Windows 10.

**Comment by jjallaire** [comment]
The very latest update to the extension resolves this issue

**Comment by bschneidr** [comment]
I'm having this issue for all of the version *after* 1.86.2.

**Comment by jjallaire** [comment]
Hi @bschneidr, as a follow up could you do the following:

(1) See if there are messages in the Debug Console when loading a qmd file

(2) Execute the Quarto: Verify Installation command to see what its output is.

(3) Post a link to a minimum reproducible example (project/files where you see this behavior). As things currently stand, we don't have any other reports of this so it seems likely that something about your particular file/project may be in play.

**Comment by bschneidr** [comment]
Thanks, @jjallaire- you were right that it was attributable to something in that particular file. In putting together a reproducible example, I learned that there was an issue particular to my file and its use of `$$` to enclose LaTeX math. The issue is closely related to: https://github.com/quarto-dev/quarto-cli/issues/1181#issuecomment-1209577766 and https://github.com/quarto-dev/quarto-cli/issues/1781. I'm not sure if this should be its own issue.

I used a `$$ ... $$` fencing for my LaTeX, where the first `$$` was at the end of a line, and the second `$$` was on its own line. The file would render without issue when I ran `quarto render`. But working interactively in VS Code, for everything below the math `$$`, none of the syntax highlighting appears and none of the code chunks can be run.

Example Quarto File:

````r
---
title: "Reproducible Example"
execute:
  warning: false
  message: false
---

The triangle inequality is simple but useful: $$
\lvert a + b \rvert \leq \lvert a \rvert + \lvert  b \rvert 
$$ 

Here is some R code so you can see for yourself:

```{r}
a <- rnorm(10)
b <- rnorm(10)

all(abs(a + b) <= abs(a) + abs(b))
``` 
````

<details><summary>Quarto Verify Installation Result</summary>

$ quarto check
A new release of Deno is available: 1.28.2 → 1.34.3 Run `deno upgrade` to install it.

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.340
      Path: C:\Users\benja\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: C:/Users/benja/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: (None)
      knitr: 1.43
      rmarkdown: 2.20

[>] Checking Knitr engine render......OK

</details>

**Comment by jjallaire** [comment]
Thanks so much for the detailed follow up! This does all make sense now as the tokenizer we use for math expressions doesn't handle display math not occurring entirely on its own line. You should be able to get identical rendering behavior and correct editor behavior if you just insert a newline after the `:` in the above example.
